### ISSUE TITLE
hosting environment not sustainable

### ISSUE THREAD

**Issue by AlbertRemke** [oer4sdi/spatial-streaming-oer#6]
Right now the module is hosted at https://digisat.space/2022 . We would either need to find a sustainable hosting environment, which can be controlled by the OER4SDI project team or a way to use the module as a stand-alone module.

**Comment by AlbertRemke** [comment]
OK, please add to the readme file in GitHub the info/recommendation that the module can be used by downloading the H5P file and viewing it with LUMI (recommended) or alternatively by using other environments such as moodle, wordpress (only for LUMI can we ensure that it really works and that there are no version conflicts). 

I would still like to provide one-click access to the runtime, but that is a lower priority. Once the H5P is released via ORCA, the link to the latest released version can also be provided on GitHub.

**Comment by purijs** [comment]
Updated Readme
